name: ThumbSir
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sleek_circular_slider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/my.png
    - images/my_big.png
    - images/circle.png
    - images/circle_s.png
    - images/back.png
    - images/back_white.png
    - images/set.png
    - images/openclient.png
    - images/openowner.png
    - images/traded.png
    - images/list.png
    - images/cake.png
    - images/home.png
    - images/analyze.png
    - images/listicon.png
    - images/bell.png
    - images/bell_yellow.png
    - images/finish.png
    - images/morning.png
    - images/noon.png
    - images/evening.png
    - images/todayplanmorning.png
    - images/todayplannoon.png
    - images/todayplanevening.png
    - images/time.png
    - images/star1.png
    - images/star2.png
    - images/star3.png
    - images/star4.png
    - images/star5.png
    - images/star1_e.png
    - images/star2_e.png
    - images/star3_e.png
    - images/star4_e.png
    - images/star5_e.png
    - images/phone.png
    - images/site.png
    - images/site_small.png
    - images/group.png
    - images/company.png
    - images/editor.png
    - images/upbtn.png
    - images/add.png
    - images/next.png
    - images/service.png
    - images/vip.png
    - images/vip_yellow.png
    - images/date.png
    - images/histogram.png
    - images/edit.png
    - images/plantoday.png
    - images/plantom.png
    - images/warn.png
    - images/warnbox.png


