name: ThumbSir
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bmflocation: ^1.0.3
  cupertino_icons: ^0.1.2
  sleek_circular_slider: ^1.1.0
  flutter_time_picker_spinner: ^1.0.6
  wheel_chooser: ^0.1.0
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  some_calendar: ^1.2.3
  city_picker: ^0.1.4
  rflutter_alert: ^1.0.3
  image_picker: ^0.6.7
  image: ^2.1.18
  simple_image_crop: ^0.1.3
  carousel_slider: ^2.1.0
  simple_autocomplete_formfield: ^0.2.7
  mime: ^0.9.6+3
  dio: 3.0.9
  fl_chart: ^0.10.0
  chips_choice: ^1.2.0
  package_info: ^0.4.1
  path_provider: ^1.6.11
  flutter_holo_date_picker: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/my.png
    - images/my_big.png
    - images/my_3.png
    - images/circle.png
    - images/circle_s.png
    - images/circle_middle.png
    - images/blue_circle.png
    - images/circle_r.png
    - images/back.png
    - images/back_white.png
    - images/back_w_arrow.png
    - images/back_select.png
    - images/next_select.png
    - images/set.png
    - images/openclient.png
    - images/openowner.png
    - images/traded.png
    - images/list.png
    - images/cake.png
    - images/home.png
    - images/home_w.png
    - images/analyze.png
    - images/analyze_s.png
    - images/teamanalyze.png
    - images/teamanalyze_s.png
    - images/listicon.png
    - images/listicon_s.png
    - images/teamlisticon.png
    - images/teamlisticon_s.png
    - images/bell.png
    - images/bell_yellow.png
    - images/finish.png
    - images/finish_big.png
    - images/morning.png
    - images/morning_tip.png
    - images/noon.png
    - images/noon_tip.png
    - images/evening.png
    - images/evening_tip.png
    - images/todayplanmorning.png
    - images/todayplannoon.png
    - images/todayplanevening.png
    - images/time.png
    - images/star1.png
    - images/star2.png
    - images/star3.png
    - images/star4.png
    - images/star5.png
    - images/star1_e.png
    - images/star2_e.png
    - images/star3_e.png
    - images/star4_e.png
    - images/star5_e.png
    - images/star1_big.png
    - images/star2_big.png
    - images/star3_big.png
    - images/star4_big.png
    - images/star5_big.png
    - images/phone.png
    - images/site.png
    - images/site_small.png
    - images/group.png
    - images/company.png
    - images/company_big.png
    - images/editor.png
    - images/upbtn.png
    - images/add.png
    - images/next.png
    - images/service.png
    - images/vip.png
    - images/vip_yellow.png
    - images/vip_blue.png
    - images/vipbg.png
    - images/invitation.png
    - images/wx.png
    - images/zfb.png
    - images/date.png
    - images/histogram.png
    - images/edit.png
    - images/plantoday.png
    - images/plantom.png
    - images/warn.png
    - images/warnbox.png
    - images/upload.png
    - images/camera.png
    - images/imgbg.png
    - images/key.png
    - images/tie.png
    - images/tie_blue.png
    - images/tie_big.png
    - images/warn_blue.png
    - images/choose.png
    - images/next_blue.png
    - images/task.png
    - images/delete.png
    - images/delete_blue.png
    - images/wait.png
    - images/surprise.gif
    - images/search.png
    - images/client.png
    - images/red_dot.png
    - images/phone_ex.jpg
    - images/gift.png
    - images/gift_deal.png
    - images/gift_festive.png
    - images/gift_birth.png
    - images/my_traded.png
    - images/my_traded_s.png
    - images/team_traded.png
    - images/team_traded_s.png


